### PR TITLE
Replace unittest with pytest in test suites

### PR DESCRIPTION
**Pull request by yuriy-os**
Deleted `unitest` occurrences in test code. Basically, the main change was an addition of fixtures in test classes and refactoring of test methods to use these fixtures.

You can run tests now like `pytest tests` from root directory.

This solves #8.

### CODE REVIEW

**Review by Benardi — CHANGES_REQUESTED** [review]
* Please make sure your code passes the pep8 (and other) testing environment 
       + This project uses CI through Tox/Travis.   
* Also, please configure the Git author in your commits, as it does not match your Github user.

**Comment by Benardi** [comment]
`@classmethod def setUpClass(cls)` in unittest should be replaced with `@pytest.fixture(scope="module")`

**Comment by yuriy-os** [comment]
- Made codestyle PEP8 compliant.
- Updated my email in commit info.

> `@classmethod def setUpClass(cls)` in unittest should be replaced with `@pytest.fixture(scope="module")`

I thought that fixture should be atomic and because of that I decided to split `@classmethod def setUpClass(cls)` contents into separate fixtures. To solve issue, that you had mentioned, I've only added `scope="module"` into every fixture decorator.

**Review by Benardi — APPROVED** [review]
All seems good

**Pull request merged**
